### ISSUE TITLE
rust.vim should respect the user's indentation style.

### ISSUE THREAD

**Issue by mortie** [rust-lang/rust.vim#105]
Currently, rust.vim changes indentation to be four spaces. Personally, I strongly prefer tabs (though please don't make this into a tabs vs spaces argument). I think rust.vim should respect the user's choice, not forcefully change indentation style to four spaces.

**Comment by chris-morgan** [comment]
Vim defaults to tabs. The standard Rust ecosystem is strongly four-spaces,
so rust.vim really needs to default to four spaces. Simply setting the
options as we do now is really just about the best way to do it.
after/syntax/rust.vim is a suitable place to override it—or if there isn't
a 'g:rust_something' option for our we could add such a thing. (I don't
have the code handy right now.)

I did put quite a lot of thought into these sorts of things some time back;
I tend to agree with you that forcing things like that isn't good, while
saying that defaulting to the standard conventions is good. It's a bit of a
balancing act.

**Comment by dengelt** [comment]
> The standard Rust ecosystem is strongly four-spaces, so rust.vim really needs to default to four spaces. 

I don't understand why this makes it necessary to override the user's settings.

**Comment by ExpHP** [comment]
Despite my *infinite, undying hatred of soft-tabs in every. single. editor. that has supported them ever*—I am going to defend CM's position in that I do not believe an unreasonable choice has not been made here.  For those individuals who don't mind either way, it is a good thing to push them towards the community standards.

**As for motivated individuals such as us who *do very much* mind, we can easily find a workaround!**

This plugin is actually a bit kinder than some, because it actually comes with [a "please don't do that" option](https://github.com/rust-lang/rust.vim/blob/fc11d02fee330df7b30c83a80f09dd0c60ab43ce/ftplugin/rust.vim#L41-L44)!  Setting `let g:rust_recommended_style = 0` in vimrc lets you keep your tabs.

Of course, there's also a bunch of other things which it will do regardless of those settings, like changing `formatoptions`.  For times like these, I usually find that [venting one's frustration into a .vim/after/ file](https://github.com/ExpHP/dotfiles/blob/master/vim/after/ftplugin/python.vim) is quite a successful strategy.  In this case, the place where you want to put your overrides is `~/.vim/after/ftplugin/rust.vim`.

**Comment by steveklabnik** [comment]
Yes, you can set that option if you don't want to use the recommended style.
