### ISSUE TITLE
delimitMate places quotes while typing lifetime specifier

### ISSUE THREAD

**Issue by euclio** [rust-lang/rust.vim#114]
Steps to reproduce:
1. Install delimitMate.
2. Type `let test = &'`.
3. The single quote is doubled.

Expected behavior: the `'` is not duplicated.

Trying to debug this, I've found that the `rustLifetimeCandidate` syntax region is not applied to this example, which delimiteMate should ignore.

**Comment by CleanCut** [comment]
I keep hitting this as well.

**Comment by da-x** [comment]
@chris-morgan can you please check if `syntax/rust.vim` can be easily fixed for this, instead of having the workaround? Thanks!

**Comment by chris-morgan** [comment]
I think there are two things at play here:

1. Some change in the syntax highlighting *somewhere* which broke rustLifetimeCandidate
2. The fix for #48 in f1c3acbf92922d26a8f9e420212be7250a0213b1;

For the first item: it looks like `keepend` needs to be added to rustLifetimeCandidate now. Also note that rustGenericRegion was just always broken, by the looks of it; I’ve fixed it locally.

For the second item: when I’ve done the first item, delimitMate is still not behaving “correctly”. I lack time to examine it now, but I suspect that fix rendered it completely non-functional. If anyone wants to try it out before I get round to dealing with it: try reverting the f1c3acbf92922d26a8f9e420212be7250a0213b1 changes, and add `keepend` to rustLifetimeCandidate region, and see if it works.

**Comment by da-x** [comment]
I applied the workaround for now.
