### ISSUE TITLE
Multiple `autocmd` on `BufWritePre` event after called `rustfmt#Format()`

### ISSUE THREAD

**Issue by ladrift** [rust-lang/rust.vim#115]
After opening a `*.rs` file and type `:autocmd BufWritePre`, I see **two** `call rustfmt#Format()` has been registered on `BufWritePre` event.
```
:au BufWritePre
--- Auto-Commands ---
BufWrite
    *.rs      call rustfmt#Format()
              call rustfmt#Format()
Press ENTER or type command to continue
```
Every time I type `:call rustfmt#Format()`, the number of `call rustfmt#Format()` on `BufWritePre` event increase one.

If I use `let g:rustfmt_autosave = 1` in `.vimrc`, everytime I `:write` a `*.rs` file. The number of `call rustfmt#Format()` was twice more (eg. 2 ot 4, 4 to 8, ...).

It creates huge delay on writing a file.

**Comment by tarrant** [comment]
I'm also experiencing this. In the past when I've encountered this issue it has been because the the `autocmds` haven't been wrapped in a `augroup`. Poking around in [ftplugin/rust.vim](https://github.com/rust-lang/rust.vim/blob/master/ftplugin/rust.vim) everything seems right but obviously something is wrong here.

I attempted to wrap just the one `autocmd` in an `augroup` and that seemed to fix it but I'd like to find the underlying issue.

**Comment by tarrant** [comment]
So found the main issue a [source on line 121](https://github.com/rust-lang/rust.vim/blob/master/ftplugin/rust.vim#L121). There is also a related issue now where it complains when it attempts to unload the augroup but the augroup isn't empty. Should have a PR with a fix for both incoming shortly.
