### ISSUE TITLE
Getting "can't find crate for ..." with Syntastic

### ISSUE THREAD

**Issue by pLesur** [rust-lang/rust.vim#130]
Hi, using syntastic with this plugin will give me the error "can't find crate for" although the crate is found properly by cargo (program compiles just fine).
This might be a syntastic configuration problem, but no mention is made in this repo about any configuration to do so here I am.

**Comment by brycefisher** [comment]
Same issue for me when using Neovim / Neomake.

**Comment by mckinnsb** [comment]
I am also getting this issue.

**Comment by yyyar** [comment]
I have the same issue with vim and vundle, anyone found a solution?

**Comment by mckinnsb** [comment]
@yyyar try my fork of rust.vim for now. It builds a new syntax checker for rust using cargo that runs "cargo build" in the directory of the file. It's a little slow the first time because it has to compile, but it works for now.

From what I understand, rustc removed the -Z --no-trans flag, which was what the old checker was using.The checker on master now just runs "rustc {file}". This was done to keep rust.vim fast, but with the new changes to cargo check, we can now run "cargo check" in the directory, and this should be almost as fast because cargo check no longer compiles ( you can read about that here ):

https://www.reddit.com/r/rust/comments/5ibr2a/cargo_check_has_been_merged_into_cargo_directly/

So you can take my fork, or try to build a new syntax checker using cargo check. rust.vim might get a PR or update fixing this soon, but I'm not sure when that would get merged into master.

**Comment by estin** [comment]
While awaiting PR #132
Overriding `rustc` checker options works for me.

```lang=vim
let g:syntastic_rust_rustc_exe = 'cargo check'
let g:syntastic_rust_rustc_fname = ''
let g:syntastic_rust_rustc_args = '--'
let g:syntastic_rust_checkers = ['rustc']
" let g:syntastic_debug = 1
" let g:syntastic_debug_file = "~/syntastic.log" 
```
By this settings would be used `cargo check --` on whole project (not for current file)

**Comment by brycefisher** [comment]
FYI @bobzoller

**Comment by ccheek21** [comment]
Update: Rust stable branch [now includes cargo check](https://blog.rust-lang.org/2017/03/16/Rust-1.16.html)

**Comment by tdbgamer** [comment]
Looks like it was fixed, but just to update this ticket, adding this line to your vimrc will fix it
`let g:syntastic_rust_checkers = ['cargo']`

**Comment by mitchmindtree** [comment]
FWIW I also had to update the syntastic plugin itself - just thought I'd add a friendly reminder!

**Comment by da-x** [comment]
Hi all, 

After various fixes to `rust.vim`, there is no longer the need to specify `g:syntastic_rust_checkers = ['cargo']`, it's now default and should just work out of the box. There were also fixes to the checker itself (for example, 'current directory' sensitivity issues). 

At last, this old issue should be done!
