### ISSUE TITLE
RustFmt fails on Cygwin due to expansion to full path not being a Windows path

### ISSUE THREAD

**Issue by pyjarrett** [rust-lang/rust.vim#158]
I am running Vim 8.0 inside Cygwin 2.8.0 under Windows 10.

Running `RustFmt` fails and just prints the contents of the current file.  Doing`%!rustfmt` works as mentioned in #154, so the executable is in the path.

The issue is caused by temporary filename created in `rustfmt#FormatRange` or `rustfmt#Format` in `autoload/rustfmt.vim`

`expand` using `:p` results in a Cygwin path starting with `/home` relative to the Cygwin root directory, vice a Windows absolute path starting at the directory letter.

I've hacked in the following replacement which works locally for me, but I'm not sure how editing from a different directory might affect it.
```
let l:tmpname = "./" . expand("%:p:t") . ".rustfmt"
```
I can't find any other Cygwin-specific code in the plugin, so I didn't want to sprinkle it around to get this to work.  I'm going to look into how to more generically solve this (or even if it is worth fixing), but I'd appreciate some recommendations.

**Comment by yasammez** [comment]
I am experiencing the same problem with vim 8.0.1376 and cygwin 2.9 on Windows 7. I am trying to use LanguageClient-neovim (also works with vim8), but every operation that involves sending a position within a file to the language server (so pretty much everything) results in the program trying to convert a cygwin path "/home/..../" to a URL by
```
Url::from_file_path(self)
```
which unconditionally fails because
1. this is a "Windows" environment and
2. the path starts neither with a drive letter like C: nor \\
