### ISSUE TITLE
Incorrect indention after the dot operator

### ISSUE THREAD

**Issue by MaikKlein** [rust-lang/rust.vim#195]
![](https://i.imgur.com/dr65Ofp.gif)

It seems if there is an indention like `.collect();`, the plugin tries to match the level of this indent which is incorrect.

**Comment by MaikKlein** [comment]
Actually the incorrect  re-indention comes from a different plugin `auto-pairs`. But pressing `O` will still place the cursor at the wrong indention level.

**Comment by chris-morgan** [comment]
Can’t reproduce under any circumstances. Can you post a complete file that demonstrates the issue?

**Comment by da-x** [comment]
I think this should do (not sure it compiles, but does not matter):

```rust
  fn main() {
      let paths: Vec<_> = ({
              fs::read_dir("test_data")
                  .unwrap()
                  .cloned()
          })
          .collect();

      println!("Hello World\n");
  }
```

**Comment by MaikKlein** [comment]
@chris-morgan The problem in the gif came from a plugin called `auto-pairs`, and the indentation for `o` is not relevant to this plugin. This issue can be closed.

**Comment by da-x** [comment]
It reproduces with the above.

BTW I am working on adding adding Vader automated tests to the CI to test indentations on various cases - I got a test written for each one of the currently open issues.

**Comment by da-x** [comment]
@MaikKlein It seems it reproduces even without auto-pairs according to my tests.

**Comment by da-x** [comment]
@chris-morgan I am halfway of trying a new `GetRustIndent()` implementation independent of `cindent` that would just work. Reason I started it is because of this example, where a long line was actually being split and the indent level we should return to after the `;` should match the one of the `let` (independent of the one of `.collect()`. Feels like a complete solution is more involved than just patching the current one.

**Comment by chris-morgan** [comment]
I’d love to experiment with daemonising rustfmt and getting it to suggest indentation for each line. (I have no idea if it can do that, but if not, it should be able to.) That seems like the only approach that’s going to be able to do everything correctly, because expressing *all* the desired formatting rules would be absurdly complex in Vimscript.

**Comment by da-x** [comment]
I'd also wish for rustfmt, to deliver, but I am not optimistic. Support for partial input or say, a "delta" indent mode in rustfmt seems limited, and may stay that way for a long time. While it currently can receive a range of lines, they must encompass a whole top-level syntactic object. Partial input also contains incomplete expressions which rustfmt needs to handle too. If it would work right for us, you'd also have to tell it when line is being edited, or where is the cursor.

BTW, I am not sure we need all the formatting rules that rustfmt provides. The reason is that rustfmt does quite a lot, seems to be designed for re-arranging the code altogether. For instance, it combines short lines and splits certain expressions to different lines. Our task is much simpler - we only need to compute the indent at the cursor without modifying the text, which is only determined by the preceding lines and perhaps the first character that the user types (if it's a new line). So it doesn't really need all the formatting rules, but only to not to deviate from them too much.

What I like about `indentexpr` is that you can easily write all the tests you need for it.
I'll make some more attempts.

**Comment by da-x** [comment]
There's now some handling for this in master. Please test!
