### ISSUE TITLE
Raw string literals support

### ISSUE THREAD

**Issue by dodomorandi** [rust-lang/rust.vim#198]
I was encountering some issues whilst using string literals in Rust. I checked inside `syntax/rust.vim` and indeed there are no `rustString` regions defined for raw string literals.

Is it possible to add this support?

**Comment by dodomorandi** [comment]
No, sorry, I did not noticed that the last `rustString` line is exactly related to raw literal strings. The question now is: why does vim (in my particular case I am using the last version of NeoVim) go crazy with delmiters? Could be that there are some strange cases in which the current expressions do not work well?

**Comment by chris-morgan** [comment]
Take a look at the `:syn-sync` help. Basically, you’re hitting a limitation of techniques that Vim uses for performance. You can opt out of it with `:syn sync fromstart`, either applied globally or just for Rust files. (No changes relating to the syn-sync value will be accepted in this repository, because they’re not *needed*, and it is frowned upon to change them in syntax files unnecessarily—it’s considered the user’s responsibility.)
