### ISSUE TITLE
Parse failed assertions using the errorformat

### ISSUE THREAD

**Issue by teoljungberg** [rust-lang/rust.vim#225]
Given a dummy file such as this in a cargo project.

```rust
fn main() -> &'static str {
    "Hello"
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn testing() {
        assert_eq!("World", main());
    }
}
```

Having my compiler set to `compiler cargo`, and I run `:make test` within vim. I would expect the error format to have parsed out the file, line and column number in my quickfix list. This does not happen.

The provided compiler plugins aught to be updated to capture this output. Since the two compilers' errorformats "inherit" from the other (or more, `cargo.vim` extends the `rustc.vim` compiler's errorformat). I'm unsure where this change fits best. I've tried to resolve this myself, without any success. Any help or aid would be much appreciated!

**Comment by da-x** [comment]
Dup of #112

**Comment by da-x** [comment]
Thanks for the feature request!

```
---- tests::testing stdout ----
        thread 'tests::testing' panicked at 'assertion failed: `(left == right)`
  left: `"World"`,
 right: `"Hello"`', src/main.rs:11:9
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

The `errorformat` setting would have to be more lenient in order to detect any `file:line:column` (or even `file:line`) type of expressions in the test output. It's a bit harder to catch than rustc messages, and also, there are various crates that extend on unit test asserting capability, such as [pretty_assertions](https://crates.io/crates/pretty_assertions), each with their own format.

Present alternatives to `formaterror` are beyond fixing rust.vim: 1) use a filter program (see `:help formaterror`), or 2) use a modified crate assert library that prints asserts with format that matches the current `formaterror`.

Anyway, I wasn't able to come up with a reasonable change to `formaterror` quickly enough, so I'd leave this open for anyone else to try.

**Comment by teoljungberg** [comment]
> The errorformat setting would have to be more lenient in order to detect any file:line:column (or even file:line)

I assume that it would be possible to match `left: VALUE file.rs:line:col` or `right ...`, and limit the matching to that. But with the testing I got it matched the entire line and tried to open that specific file. Which didn't pan out.

> there are various crates that extend on unit test asserting capability, such as pretty_assertions, each with their own format

Valid point, but if a crate extends the asserting output. I would expect it to break the `errorformat` parsing. So I would say that's an OK trade-off to make.

> 2) use a modified crate assert library that prints asserts with format that matches the current formaterror.

I would say it's a short term solution to use a crate for this, as I would expect the `rust.vim` plugin to be able to handle `rust` + `cargo` out of the box.

**Comment by teoljungberg** [comment]
BUT, if there's a crate I can use short term to get this to work - I'd be a happy camper!

**Comment by da-x** [comment]
Reading the Vim docs a bit more, I finally did come with something to match the assert, in the PR referenced here.

@teoljungberg see if it works for you?

**Comment by teoljungberg** [comment]
#226 works wonders! Thank you @da-x
