### ISSUE TITLE
Rust Vim is "arbitrarily" moving the cursor

### ISSUE THREAD

**Issue by omarabid** [rust-lang/rust.vim#299]
I'm using Rust Vim with vundle, so I think I have the latest version. In brief, my cursor went crazy. Here is a very simple example.

I'm on a line, I press enter and I write "use ". Notice the space at the end. What Rust Vim does, is move the cursor from after the space, to before the space. I don't know, or I'm not aware of how useful this is.

Write

"use *"

Becomes

"use*"

Obviously this drove me crazy and I spent a couple of hours trying to find the culprit here, which surprisingly turned out to be Rust Vim.

**Comment by da-x** [comment]
The problem lies in the combination of having `let g:rustfmt_autosave = 1` and `vim-scripts/vim-auto-save'` with `let g:auto_save_in_insert_mode = 1` in your configuration (it's good to have your config on Github :). With `let g:auto_save_in_insert_mode = 0` it works okay.

What `vim-auto-save` is trying to do while in insert mode is - perform save, and then go back into insert mode quickly enough so that the user isn't bugged. It manages to do so successfully without losing cursor position only if `rust.vim` does not get in the way trying to perform reformatting of the file. Perhaps there's a workaround for this, but I'm not sure which way to pursue yet.

**Comment by omarabid** [comment]
@da-x I think this is a bit late but the issue was resolved. I apologize for forgetting to report back.
