### ISSUE TITLE
Automatic syntax highlighting with .rs files does not work

### ISSUE THREAD

**Issue by alkorang** [rust-lang/rust.vim#306]
**rust.vim version:**
commit 12f549f9e4939bca53c8a87e6921a36fb143af9a

**Steps to reproduce:**

On CentOS 7, install vim 7.4
```
# yum install vim-enhance vim-common
```

Then, install rust.vim using vim-plug
```
$ curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
```
`~/.vimrc` file:
```
call plug#begin('~/.vim/plugged')
Plug 'rust-lang/rust.vim', { 'tag' : '12f549f9e4939bca53c8a87e6921a36fb143af9a' }
call plug#end()
```

After saved `~/.vimrc`, run `:PlugInstall` in vim or `$ vim +PlugInstall +qall` on terminal.

**Expected vs. actual behavior:**

* Expected:
When I opened rust source file with .rs extension, for example `main.rs`, then vim automatically highlights Rust syntax.
(And this is the actual behavior until commit 329fa788f56977d73ff958388b8e08ea7bb885f3.)
![image](https://user-images.githubusercontent.com/11420879/52477963-1ddd6880-2be7-11e9-9ec6-0ac795cfe5e6.png)

* Actual:
With commit 12f549f9e4939bca53c8a87e6921a36fb143af9a, vim automatically highlights syntax but it is not for Rust.
![image](https://user-images.githubusercontent.com/11420879/52477998-41081800-2be7-11e9-8cd9-287c5a68ca83.png)
When I run `:set syntax=rust` manually, then Rust syntax highlight works.

I cannot get additional debug information because `:RustInfo` failed with E492 error.
![image](https://user-images.githubusercontent.com/11420879/52478514-ecfe3300-2be8-11e9-81c8-4acc593e9345.png)

**Comment by chris-morgan** [comment]
I can’t reproduce this on Vim 8.1.1 on Windows, probably for the reasons mentioned below.

This smells like another ftdetect rule butting in first, thereby triggering exactly the deliberate and intended difference between `setfiletype rust` and `set filetype=rust`.

Please run this to determine what the filetype actually *is* on a .rs file, and where it was last set:

```
:verbose set filetype?
```

Working from distant memories of such truly ancient versions of Vim worked out of the box, I expect the answer will be hercules from $VIMRUNTIME/filetype.vim. (For I observe even now that my own Vim has it set to rust from $VIMRUNTIME/filetype.vim rather than the rust.vim ftdetect.vim, suggesting that it’s currently basically only working because Vim already knows about Rust.)

I shan’t look into it now, but we may need to do some autocmd group rejiggering or something to gain higher priority than it (if that’s possible), without clobbering it altogether (because `set filetype=rust` *is* still definitely the wrong thing to do, even if this may now explain why it was that way). I’ll think about it more some other time, probably at least a few days hence. If suitable augroup fiddling isn’t possible, maybe we just clobber it iff filetype=hercules.

**Comment by chris-morgan** [comment]
Oh, and about the `:RustInfo`: that’s from ftplugin/rust.vim, so it’s only available once you load a Rust file.

**Comment by alkorang** [comment]
> Please run this to determine what the filetype actually _is_ on a .rs file, and where it was last set:
> 
> ```
> :verbose set filetype?
> ```

@chris-morgan The output of `:verbose set filetype?` with `main.rs` is:
```
  filetype=hercules
        Last set from /usr/share/vim/vim74/filetype.vim
Press ENTER or type command to continue

```
