### ISSUE TITLE
Causes Vim to hang if a parent directory contains spaces

### ISSUE THREAD

**Issue by ipetkov** [rust-lang/rust.vim#31]
Opened up a Rust file somewhere in the current directory while a few parent directories up had a space in it. I'm not sure where the hang happens but I think the plugin gets stuck in a loop while processing the whole path. Replacing the spaces with a different character makes the issue go away.

**Comment by chris-morgan** [comment]
I cannot reproduce this, not can I imagine anything in the code that would lead to that. I think it most likely to be something else that is the problem here, though possibly through interaction with rust.vim. When it hangs, you should be able to interrupt it with Ctrl+C and, presuming it is in Vim code, it will show a trace of where it was at that point; could you please try doing that and post what it says?

**Comment by ipetkov** [comment]
@chris-morgan In trying to reproduce I found out it's definitely a cargo issue: it gets stuck in a loop if a parent directory has spaces, so if the plugin calls cargo at any point it will get stuck too. I'll open up an issue there, sorry for the confusion!
