### ISSUE TITLE
Remove the "<:>" in &matchpairs

### ISSUE THREAD

**Issue by tanhuacheng** [rust-lang/rust.vim#350]
as i am use the *delimiMate* plugin, this cause auto close(by insert a `>`) when i type `<` in a  .rs file.

due to *delimiMate* uses the values in `matchpairs` to identify the pairs. so, we should remove the character `<` in `matchpairs`.

**Comment by chris-morgan** [comment]
The inclusion of `<:>` in matchpairs has been discussed a couple of times because of unmatched usages (`=>` and inequality operators), and we’ve decided to keep it, because its presence is more useful on generics than is its troublesomeness on other things. So we’re not removing it for delimitMate’s sake.

I have no intention of doing this myself (I *hate* delimiter auto-insertion, every implementation I’ve ever tried causes way more trouble than the benefit it provides), but we do accept alterations that don’t harm functionality for for other users. Take a look at autoload/rust/delimitmate.vim for various tweaks for delimitMate that already exist—which may be useful guidance for yourself, even if whatever change you end up with isn’t suitable for inclusion here.
