### ISSUE TITLE
Regression?: Cargo commands open in a new buffer

### ISSUE THREAD

**Issue by alercah** [rust-lang/rust.vim#376]
I recently went back to a setup that I haven't used since maybe February or March, and I naturally had to update everything. When I did, I noticed that rust.vim's various cargo commands, like `Cbuild`, `Cargo`, etc. now output to a separate buffer, as opposed to just outputting like normal `!` commands do.

This might not be *so* bad if it re-used the buffer, though it would still be a pain on small screens, but it does not. Every single invocation opens a new buffer, which means that every buffer must be manually closed. It's easier for me just to write "!cargo build".

I can't see an option in the docs to turn this off, so I personally consider it a serious usability regression.

**Comment by da-x** [comment]
This is due to #361. Wasn't aware that the old behavior is preferred. @rhysd, please provide a fix?

**Comment by rhysd** [comment]
ok, let me check this.

**Comment by rhysd** [comment]
That's because the `cargo ...` command is no longer run with `:!` command. Now it is run with `:terminal` command for better shell command integration.

- The command is better when you're using GUI Vim since `:!` on GUI Vim does not give colorful output.
- Showing the command with separate window is useful when you get some compilation errors. You can see your code and the command results at the same time.

But as @alercah said, with small screen it would not be helpful. I think it is depending on the amount of output from command so plugin side cannot easily determine which `:terminal` or `:!` should be used.

My suggestion is adding a variable which configures a command to run shell commands. For example:

```vim
# Run with :!
let g:rust_shell_command_runner = '!'

# Run with :terminal
let g:rust_shell_command_runner = 'terminal'
```

What do you think, @alercah and @da-x? If you feel ok, I'll make a pull request.

**Comment by alercah** [comment]
That's one alternative, but I think I would be happy with the current behaviour if reuse, at least, were an option (I think this is done with the `termopen` function, from some quick googling). My personal ideal would be a quickfix buffer, but I don't know how viable that actually is given that quickfixes are their own kind of special. My personal ideal, though, I'd get some sort of "jump to first error" behaviour similar to quickfixes, with a buffer containing the output that could be hidden by default (say, `COut` to open up that buffer and look at it).

**Comment by da-x** [comment]
@rhysd please make PR, for either `termopen` fix or `g:rust_shell_command_runner`?

**Comment by Ghosty141** [comment]
A big problem for me is that it takes more keystrokes which is quite noticeable for something you do as often as building and running your code. Using the old behavior I mostly did the following:
SHIFT+. ARROWUP ENTER => check what went wrong => ENTER
This resulted in quite fewer keystrokes. Another problem for me is that the new buffer sometimes doesn't fit in nicely because there are other windows already open thus its size is quite small and I have to resize it first before being able to check the error messages.

An option to toggle this would be great!

**Comment by rhysd** [comment]
I apologize that I missed the notification.. Let me take a look at this when I come home.

@Ghosty141 

You can add mapping to close terminal window quickly as follows.

```vim
Autocmd TerminalOpen * if &buftype ==# 'terminal'|nnoremap q :q<CR>|endif
```

Anyway, I'll make the behavior configurable

**Comment by Pobega** [comment]
Note to anyone who may run across this via Google (like me)

If you want to open the terminal output in a new tab rather than a window you can use the `tab` command:
```vim
let g:cargo_shell_command_runner = 'tab :terminal'
```

**Comment by Arnie97** [comment]
Yet another note to anyone who may run across this via Google:

An alternative way to reuse the same buffer for cargo outputs is the [quickfix](https://vimhelp.org/quickfix.txt.html) **`:make`** command.
In rust.vim, `&makeprg` is already set to `cargo $*`, so we could just use `:make b` for `:Cargo b` or `:Cbuild`.

I would prefer this approach, because it's much more handy to jump between errors leveraging `:cn` `:cp` commands (or 3rd-party plugins that works together with quickfix).
