### ISSUE TITLE
Turn off error checking

### ISSUE THREAD

**Issue by yarikbratashchuk** [rust-lang/rust.vim#413]
Hello and thanks for this great plugin)

I'm just wondering if there is a way to turn off error checking or make it a separate command?
I find this a bit annoying to have red highlighting pop up while I'm still typing, and it feels like it also slows down the process a bit.

**Comment by pizzamig** [comment]
Hi. Did you find the root cause of it or a workaround?
I tried to disable rustfmt (I though it was the reason of the error checking) setting `rustfmt_command='true'` , but with no luck.
checking the syntax while typing is a bit annoying and sometimes I have entire blocks marked as red and they are not really readable anymore...
