### ISSUE TITLE
Code should be highlighted in doc comments, perhaps through a setting.

### ISSUE THREAD

**Issue by euclio** [rust-lang/rust.vim#63]
This is done by https://github.com/tpope/vim-markdown, so it might be helpful to start there.

**Comment by da-x** [comment]
Pushed! Currently limited to `///` and `//!` blocks, and assumes Rust. Enable by default.

Check an example:
```
wget https://raw.githubusercontent.com/rust-lang/rust/master/src/libstd/sync/mpsc/mod.rs
vim mod.rs +63
```

**Comment by chris-morgan** [comment]
I’ve pushed improvements to @da-x’s implementation in b508cb149da34209cce089a7f483a86c07534567, to:

- only highlight it as Rust if rustdoc would treat it as Rust (I lifted the algorithm from rust’s src/librustdoc/html/markdown.rs);
- support highlighting in indented comments (essentially, `^///` → `^\s*///`);
- support block comments (`/** … */` and `/*! … */`);
- highlight the code fence lines (by default) as SpecialComment, rather than as nothing.

Known limitations that are very unlikely to ever be addressed:

- Indented (rather than fenced) code blocks are not supported:

    ```rust
    /// Like this:
    ///
    ///     println!("Hello, world!");
    ```

- The highlighting of the `///` or ` * ` inside multi-line syntax elements (notably, multi-line strings) gets mangled:

    ```rust
    /// ```
    /// println!("Hello,
    /// ← mishighlighted slashes!");
    /// ```
    ```

- A leading ` * `, if used in block comments that *aren’t* using leading `*` markers, is mishighlighted as SpecialComment rather than Operator:

    ```rust
    /**
     * ```
     * println!("This star to the left is correct.");
     * ```
     */
    /**
    ``` 
    println!("{}", 1
    * 1);  // ← but this one isn’t.
    ``` 
    */
    ```

**Comment by da-x** [comment]
Thanks!
