### ISSUE TITLE
:RustFmt pager

### ISSUE THREAD

**Issue by felixSchl** [rust-lang/rust.vim#68]
Hi, it appears as if the output generated by `:RustFmt` gets loaded into the pager, and I have to hit `q` to have it disappear and continue editing. Is there a way to avoid that happening?

**Comment by pyjarrett** [comment]
I had the same issue on OS X due to not having the rustfmt tool installed.  Following aggrolite's install instructions in #60 fixed the problem.

**Comment by joelpet** [comment]
Perhaps give an informational error message that `rustfmt` command was not found when running `:RustFmt`? Reading `:help executable` it seems we could use that to check if `rustfmt` exists before proceeding to call it.

For me (before installing `rustfmt`) the buffer content was simply echoed to systemlist and I had to press a button to continue editing, which I thought was the intended behavior, simply because I couldn't tell `rustfmt` was not running.

**Comment by hauleth** [comment]
Actually I have `rustfmt` installed. `:!which rustfmt` returns proper path, and still this error occurs.

**Comment by jgallagher** [comment]
I'm seeing the same thing with a new enough vim and `rustfmt` 0.5.0 installed. Tracked it down to `rustfmt` emitting this output for my file:

```
Rustfmt failed at src/types/.chrono.rs.rustfmt:71: line exceeded maximum length (sorry)
```

with a non-zero exit code. I'm not sure if this is a `rustfmt` issue or a `rust.vim` issue, but it seems like this is more of a warning than a failure. This also results in `rust.vim` leaving the `.foo.rs.rustfmt` file around (which has been mostly reformatted, except for line 71 in my case).

**Comment by nrc** [comment]
We changed Rustfmt between 0.4 and 0.5 to emit different error codes, see https://github.com/rust-lang-nursery/rustfmt#running for details. I guess Rust.vim should only bail out if Rustfmt returns 1 or 2 rather than != 0. The motivation here is for CI and so forth that want to ensure that source is formatted correctly.
